package client;

import adt.*;
import entity.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author jingh
 */
public class EventRegistrationDriver extends javax.swing.JFrame {

    private DLListInterface<Event> eventList = new DLList<>();
    private final EventFile eventFile = new EventFile();

    /**
     * Creates new form EventRegistration
     */
    public EventRegistrationDriver() {
        initComponents();

        // sets current date as minimum selectable date
        jdcDate.setMinSelectableDate(new Date());
        
        // sets max selectable date
        Calendar cal = Calendar.getInstance();    
        cal.add(Calendar.YEAR, 1); // to get next year + 1
        Date nextYear = cal.getTime();
        jdcDate.setMaxSelectableDate(nextYear);
        
        //read existing data from file
        eventList = eventFile.reader("Event.dat");

        // read from society file and Inititalize society selection
        DLListInterface<String> societyList = new DLList<>();
        societyList.add("LDDS");
        societyList.add("Computer Science");
        societyList.add("Music");
        societyList.add("Japanese Language");

        for (int i = 0; i < societyList.size(); i++) {
            jcbSociety.addItem((String)societyList.getEntry(i + 1));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbSociety = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfOrgName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jtfEventName = new javax.swing.JTextField();
        jcbCategory = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Date date = new Date();

        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jsFromTime = new javax.swing.JSpinner(sm);
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Date date2 = new Date();

        SpinnerDateModel sm2 =
        new SpinnerDateModel(date2, null, null, Calendar.HOUR_OF_DAY);
        jsToTime = new javax.swing.JSpinner(sm2);
        jbtNext = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtfNoParticipant = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Category");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Category");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Date");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Event Registration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Society");
        jPanel1.add(jLabel2);

        jcbSociety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSocietyActionPerformed(evt);
            }
        });
        jPanel1.add(jcbSociety);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Organizer Name");
        jPanel1.add(jLabel3);

        jtfOrgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOrgNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtfOrgName);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 107, 107));
        jLabel4.setText("General Details");
        jPanel1.add(jLabel4);
        jPanel1.add(jSeparator1);
        jPanel1.add(jSeparator3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 107, 107));
        jLabel5.setText("Event Details");
        jPanel1.add(jLabel5);
        jPanel1.add(jSeparator4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6);

        jtfEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEventNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtfEventName);

        jcbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meeting", "Workshop", "Fund Raising", "Talk", "Annual General Meeting", "One-day Camp", "Competition", "Seminar", "Sports Carnival" }));
        jcbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(jcbCategory);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Category");
        jPanel1.add(jLabel9);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Date");
        jPanel1.add(jLabel13);

        JSpinner.DateEditor de = new JSpinner.DateEditor(jsFromTime, "HH:mm");
        jsFromTime.setEditor(de);
        jPanel1.add(jsFromTime);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("From");
        jPanel1.add(jLabel15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("To");
        jPanel1.add(jLabel17);

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(jsToTime, "HH:mm");
        jsToTime.setEditor(de2);
        jPanel1.add(jsToTime);

        jbtNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtNext.setText("Next");
        jbtNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNextActionPerformed(evt);
            }
        });
        jPanel1.add(jbtNext);

        jbtCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbtCancel);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("No. of Participants");
        jPanel1.add(jLabel11);

        jtfNoParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNoParticipantActionPerformed(evt);
            }
        });
        jPanel1.add(jtfNoParticipant);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Time");
        jPanel1.add(jLabel18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNextActionPerformed
        Event event = new Event();
        boolean datecomplete;
        boolean timecomplete;
        boolean pnumcomplete;
        int participantNum = 0;

        if (!jtfEventName.getText().isBlank() && !jtfOrgName.getText().isBlank()) {
            
            String society = (String) jcbSociety.getSelectedItem();
            String organizer = jtfOrgName.getText();
            String name = jtfEventName.getText();
            String category = (String) jcbCategory.getSelectedItem();
            try {
                participantNum = Integer.parseInt(jtfNoParticipant.getText());
                if (event.validateParticipantNum(participantNum)) {
                    pnumcomplete = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Number of participants cannot less than" + Event.getMinNumOfParticipant() +
                            "and more than " + Event.getMaxNumOfParticipant(),
                            "Alert", JOptionPane.WARNING_MESSAGE);
                    jtfNoParticipant.grabFocus();
                    pnumcomplete = false;
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Only number is allowed in No. of participants column.",
                        "Alert", JOptionPane.WARNING_MESSAGE);
                jtfNoParticipant.grabFocus();
                pnumcomplete = false;
            }

            Calendar cal = Calendar.getInstance();
            LocalDate eventDate = null;

            if (jdcDate.getDate() == null) {
                datecomplete = false;
                JOptionPane.showMessageDialog(this, "Incomplete Information", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                datecomplete = true;
                // default format = Mar 12, 2021
                cal.setTime(jdcDate.getDate());

                // get date
                eventDate = LocalDate.of(cal.get(Calendar.YEAR),
                        cal.get(Calendar.MONTH)+1, cal.get(Calendar.DAY_OF_MONTH));
            }

            // get start time           
            cal.setTime((Date) jsFromTime.getValue());

            // startTime format = HH:MM
            LocalTime startTime = LocalTime.of(cal.get(Calendar.HOUR_OF_DAY), cal.get(Calendar.MINUTE));

            // get endTime
            cal.setTime((Date) jsToTime.getValue());

            // endTime format = HH:MM
            LocalTime endTime = LocalTime.of(cal.get(Calendar.HOUR_OF_DAY), cal.get(Calendar.MINUTE));

            // validate time
            if (endTime.isBefore(startTime) || endTime.equals(startTime)) {
                JOptionPane.showMessageDialog(this, "Event end time cannot equal or before start time",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
                timecomplete = false;
            } else if (!event.validateEndTime(endTime) || !event.validateStartTime(startTime)) {
                JOptionPane.showMessageDialog(this, "Event time is only allowed from " + Event.getStartTimeLimit()
                        + " to " + Event.getEndTimeLimit(),
                        "ERROR", JOptionPane.ERROR_MESSAGE);
                timecomplete = false;
            } else {
                timecomplete = true;
            }

            if (pnumcomplete == true && datecomplete == true && timecomplete == true) {
                event.setSociety(society);
                event.setOrganizer(organizer);
                event.setCategory(category);
                event.setName(name);
                event.setDate(eventDate);
                event.setNumOfParticipant(participantNum);
                event.setStartTime(startTime);
                event.setEndTime(endTime);

                // if the list is 
                try {
                    if (eventList.isEmpty() || !eventList.contains(event)) {
//                        eventList.add(event);
//                        // save to file
//                        eventFile.writer(event, "Event.dat");
//                        JOptionPane.showMessageDialog(this, "OK", "ERROR", JOptionPane.ERROR_MESSAGE);
                            new VenueBooking(event).setVisible(true);
                            this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "This event already created before", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "File error", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Incomplete Information", "ERROR", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_jbtNextActionPerformed

    private void jcbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCategoryActionPerformed

    private void jtfEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEventNameActionPerformed

    private void jtfOrgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOrgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOrgNameActionPerformed

    private void jcbSocietyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSocietyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSocietyActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        this.dispose();

    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jtfNoParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNoParticipantActionPerformed

    }//GEN-LAST:event_jtfNoParticipantActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventRegistrationDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventRegistrationDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtNext;
    private javax.swing.JComboBox<String> jcbCategory;
    private javax.swing.JComboBox<String> jcbSociety;
    private javax.swing.JSpinner jsFromTime;
    private javax.swing.JSpinner jsToTime;
    private javax.swing.JTextField jtfEventName;
    private javax.swing.JTextField jtfNoParticipant;
    private javax.swing.JTextField jtfOrgName;
    // End of variables declaration//GEN-END:variables


}
