package client;

import adt.DLList;
import adt.DLListInterface;
import entity.Event;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JLabel;

/**
 *
 * @author Jing Hui
 */
public class EventSummary extends javax.swing.JFrame {

    private DLListInterface<Event> eventList = new DLList<>();
         private EventFile eventFile = new EventFile();
         
    public EventSummary() {
        initComponents();
        eventList = eventFile.reader("Event.dat");
        this.getContentPane().setBackground(Color.WHITE);
        displaySummary();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitle = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbMay = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlbJun = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlbNov = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlbDec = new javax.swing.JLabel();
        jlbJul = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlbAug = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jlbSep = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jlbJan = new javax.swing.JLabel();
        jlbOct = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtClose = new javax.swing.JButton();
        jlbFeb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbMar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbApr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("Summary");
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 555, 60));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("May");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 74, 32));

        jlbMay.setBackground(new java.awt.Color(255, 255, 255));
        jlbMay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbMay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMay.setText("1");
        jlbMay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 74, 32));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("June");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 74, 32));

        jlbJun.setBackground(new java.awt.Color(255, 255, 255));
        jlbJun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbJun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbJun.setText("1");
        jlbJun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbJun, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 74, 32));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("November");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 74, 32));

        jlbNov.setBackground(new java.awt.Color(255, 255, 255));
        jlbNov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbNov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNov.setText("1");
        jlbNov.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbNov, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 74, 32));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("December");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 74, 32));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("July");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 74, 32));

        jlbDec.setBackground(new java.awt.Color(255, 255, 255));
        jlbDec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbDec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDec.setText("1");
        jlbDec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 74, 32));

        jlbJul.setBackground(new java.awt.Color(255, 255, 255));
        jlbJul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbJul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbJul.setText("1");
        jlbJul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbJul, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 74, 32));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("August");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 74, 32));

        jlbAug.setBackground(new java.awt.Color(255, 255, 255));
        jlbAug.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbAug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAug.setText("1");
        jlbAug.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbAug, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 74, 32));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("September");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 74, 32));

        jlbSep.setBackground(new java.awt.Color(255, 255, 255));
        jlbSep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbSep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSep.setText("1");
        jlbSep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 74, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("January");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 74, 32));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("October");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 74, 32));

        jlbJan.setBackground(new java.awt.Color(255, 255, 255));
        jlbJan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbJan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbJan.setText("1");
        jlbJan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbJan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 74, 32));

        jlbOct.setBackground(new java.awt.Color(255, 255, 255));
        jlbOct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbOct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbOct.setText("1");
        jlbOct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbOct, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 74, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("February");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 74, 32));

        jbtClose.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jbtClose.setText("Close");
        jbtClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 120, 39));

        jlbFeb.setBackground(new java.awt.Color(255, 255, 255));
        jlbFeb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbFeb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbFeb.setText("1");
        jlbFeb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbFeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 74, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("March");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 74, 32));

        jlbMar.setBackground(new java.awt.Color(255, 255, 255));
        jlbMar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbMar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMar.setText("1");
        jlbMar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 74, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("April");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 74, 32));

        jlbApr.setBackground(new java.awt.Color(255, 255, 255));
        jlbApr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbApr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbApr.setText("1");
        jlbApr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlbApr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 74, 32));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventSummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtClose;
    private javax.swing.JLabel jlbApr;
    private javax.swing.JLabel jlbAug;
    private javax.swing.JLabel jlbDec;
    private javax.swing.JLabel jlbFeb;
    private javax.swing.JLabel jlbJan;
    private javax.swing.JLabel jlbJul;
    private javax.swing.JLabel jlbJun;
    private javax.swing.JLabel jlbMar;
    private javax.swing.JLabel jlbMay;
    private javax.swing.JLabel jlbNov;
    private javax.swing.JLabel jlbOct;
    private javax.swing.JLabel jlbSep;
    private javax.swing.JLabel jlbTitle;
    // End of variables declaration//GEN-END:variables

    private void displaySummary() {
        int[] monthArr = new int[12];
        Event currentEvent;
        int year = Calendar.getInstance().get(Calendar.YEAR);
        
        jlbTitle.setText("<html>Number of events for each month in year " + Integer.toString(year) + "</html>");
        
        while(!eventList.isEmpty()){
           currentEvent = eventList.poll();
                              
            if (currentEvent.getDate().getYear() == year) {
                monthArr[currentEvent.getDate().getMonthValue()-1]++;
           }         
        }
        
        JLabel[] labels = new JLabel[]{jlbJan, jlbFeb, jlbMar, jlbApr, jlbMay, jlbJun, 
                            jlbJul, jlbAug,jlbSep,jlbOct,jlbNov,jlbDec};
        
        for (int i = 0; i < 12; i++) {
            labels[i].setText(Integer.toString(monthArr[i]));
        }
    }
}
