package client;

import adt.SortedArrayList;
import adt.SortedListInterface;
import entity.Society;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Msi
 */
public class SocietyDriver extends javax.swing.JFrame {

    private static SortedListInterface<Society> societyList = new SortedArrayList<>();
    SocietyFile societyFile = new SocietyFile();
    
    /** Creates new form AddSocietyDriver */
    public SocietyDriver() {
        initComponents();
        displaySociety();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelDateReg = new javax.swing.JLabel();
        jLabelFeesPerMember = new javax.swing.JLabel();
        jLabelMembers = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldNewID = new javax.swing.JTextField();
        jTextFieldNewName = new javax.swing.JTextField();
        jTextFieldDateReg = new javax.swing.JTextField();
        jTextFieldFees = new javax.swing.JTextField();
        jTextFieldMembers = new javax.swing.JTextField();
        jLabelEmptyID = new javax.swing.JLabel();
        jLabelEmptyDateReg = new javax.swing.JLabel();
        jLabelEmptyFees = new javax.swing.JLabel();
        jLabelEmptyMembers = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelTitle.setText("Add Society");

        jLabelID.setText("ID");

        jLabelName.setText("Name");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Date Reg", "Fees", "Members"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelDateReg.setText("Date Register");

        jLabelFeesPerMember.setText("Fees per member");

        jLabelMembers.setText("Target Members number");

        jButtonAdd.setText("Add ");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");

        jButton1.setText("Back to Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCancel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelDateReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabelFeesPerMember, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMembers))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNewName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldNewID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabelEmptyID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonAdd)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldFees, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelEmptyFees, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelEmptyMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldDateReg, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelEmptyDateReg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)
                        .addComponent(jLabelTitle)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldNewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmptyID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateReg)
                    .addComponent(jTextFieldDateReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmptyDateReg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFeesPerMember)
                    .addComponent(jTextFieldFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmptyFees))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMembers)
                    .addComponent(jTextFieldMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmptyMembers))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        societyList = societyFile.reader("SocietyList.txt");
        boolean nameSuccessful = false;
        boolean idSuccessful = false;

        if (jTextFieldNewName.getText().trim().isEmpty()
                && jTextFieldDateReg.getText().trim().isEmpty()
                && jTextFieldFees.getText().trim().isEmpty()
                && jTextFieldMembers.getText().trim().isEmpty()) {
            jLabelEmptyID.setText("Name is empty");
            jLabelEmptyDateReg.setText("Date register is empty");
            jLabelEmptyFees.setText("Fees is empty");
            jLabelEmptyMembers.setText("Members is empty");

        } else if (jTextFieldNewName.getText().trim().isEmpty()) {
            jLabelEmptyID.setText("Name is empty");
        } else if (jTextFieldDateReg.getText().trim().isEmpty()) {
            jLabelEmptyDateReg.setText("Date register is empty!");
        } else if (jTextFieldFees.getText().trim().isEmpty()) {
            jLabelEmptyFees.setText("Fees is empty!");
        } else if (jTextFieldMembers.getText().trim().isEmpty()) {
            jLabelEmptyMembers.setText("Members is empty!");
        } else {

            try {
                String name = jTextFieldNewName.getText();
                String dateReg = jTextFieldDateReg.getText();
                int id = Integer.parseInt(jTextFieldNewID.getText());
                double fees = Double.parseDouble(jTextFieldFees.getText());
                int targetMemNum = Integer.parseInt(jTextFieldMembers.getText());
                name = name.toUpperCase();
                Society newSociety = new Society(id, name, dateReg, fees, targetMemNum, 0);

                for (int j = 1; j <= societyList.getLength(); j++) {
                    if (jTextFieldNewID.equals(societyList.getEntry(j).getSocietyID())) {
                        JOptionPane.showMessageDialog(null, "Society already existed");
                        idSuccessful = false;
                    } else {
                        idSuccessful = true;
                    }
                }

                for (int i = 1; i <= societyList.getLength(); i++) {
                    if (name.equals(societyList.getEntry(i).getSocietyName())) {
                        JOptionPane.showMessageDialog(null, "Society already exists!");
                        nameSuccessful = false;
                        break;
                    } else {
                        nameSuccessful = true;
                    }
                }

                if (nameSuccessful && idSuccessful) {
                    societyList.add(newSociety);
                    societyFile.writer(newSociety, "SocietyList.txt");
                    JOptionPane.showMessageDialog(null, "Added successfully!");
                    clearForm();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Unable to add new society");
                    this.dispose();
                }
            } catch (HeadlessException | NumberFormatException e) {
                System.out.println("" + e);

            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new MainMenu().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocietyDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocietyDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocietyDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocietyDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocietyDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelDateReg;
    private javax.swing.JLabel jLabelEmptyDateReg;
    private javax.swing.JLabel jLabelEmptyFees;
    private javax.swing.JLabel jLabelEmptyID;
    private javax.swing.JLabel jLabelEmptyMembers;
    private javax.swing.JLabel jLabelFeesPerMember;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMembers;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDateReg;
    private javax.swing.JTextField jTextFieldFees;
    private javax.swing.JTextField jTextFieldMembers;
    private javax.swing.JTextField jTextFieldNewID;
    private javax.swing.JTextField jTextFieldNewName;
    // End of variables declaration//GEN-END:variables

    private void displaySociety() {

        DefaultTableModel societyTable = (DefaultTableModel) jTable1.getModel();
        while (societyTable.getRowCount() > 0) {
            societyTable.removeRow(0);
        }

        societyList = societyFile.reader("SocietyList.txt");
        String id;
        String name;
        String dateReg;
        String fees;
        String targetMemNum;
        String currentMemNum;

        for (int i = 1; i <= societyList.getLength(); i++) {
            id = Integer.toString(societyList.getEntry(i).getSocietyID());
            name = societyList.getEntry(i).getSocietyName();
            dateReg = societyList.getEntry(i).getDateReg();
            fees = Double.toString(societyList.getEntry(i).getFeesPerPerson());
            targetMemNum = Integer.toString(societyList.getEntry(i).getTargetMemNum());
          
            String[] data = {id, name, dateReg, fees, targetMemNum};
            societyTable.addRow(data);
        }
    }

    private void clearForm() {
        jTextFieldNewID.setText("");
        jTextFieldNewName.setText("");
        jTextFieldDateReg.setText("");
        jTextFieldFees.setText("");
        jTextFieldMembers.setText("");
             
        displaySociety();    
                    
    }

}
